### ISSUE TITLE
In progress / todo

### ISSUE THREAD

**Issue by Crispy-Cream** [GmBodhi/shandler#25]
# Need to do

# Done

### Documentation 

- [x] Drop down documentation 
- [x] Defer docs
- [x] Exclude files 
- [x] Remake the whole documentation system
- [x] button.reply
- [x] button.update 
- [x] `<interaction>.isComponent();` 
- [x] `<interaction>.isCommand();` 
- [x] Add links for examples to Shandler Example Bot when done. 

### Testing 
- [x] Test interaction.defer();
- [x] exclude files

### Shandler Example Bot

- [x] re-make and update it.

**Comment by Crispy-Cream** [comment]
When running the newest version, the error

**Comment by Crispy-Cream** [comment]
Running slash commands will throw: 

```js
(node:15268) UnhandledPromiseRejectionWarning: Error: TypeError: Cannot read property 'run' of undefined
    at C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\shandler\js\index.js:203:19
    at WebSocketManager.<anonymous> (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\shandler\js\index.js:205:11)
    at WebSocketManager.emit (events.js:327:22)
    at WebSocketShard.onMessage (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\discord.js\src\client\websocket\WebSocketShard.js:296:56)
    at WebSocket.onMessage (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\ws\lib\websocket.js:834:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\ws\lib\receiver.js:437:14)
    at Receiver.getData (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\ws\lib\receiver.js:367:17)
    at Receiver.startLoop (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\ws\lib\receiver.js:143:22)
    at Receiver._write (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\ws\lib\receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
    at TLSSocket.socketOnData (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\ws\lib\websocket.js:909:35)
    at TLSSocket.emit (events.js:315:20)
(node:15268) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)```

**Comment by Crispy-Cream** [comment]
Notes: 

EXCLUDE: 
> In exclude you must use the file name e.g: `file` not `file.js`

**Comment by Crispy-Cream** [comment]
Bug: 

In the buttonClick `button.reply('')` now edits the message instead of replying.

**Comment by Crispy-Cream** [comment]
Using button.defer in a buttonClick event, the error will be thrown: 

```js
(node:14472) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure 'undefined' as it is undefined.
    at Interaction.defer (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\shandler\js\interaction.js:108:15)
    at Client.<anonymous> (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\index.js:85:12)
    at Client.emit (events.js:327:22)
    at WebSocketManager.<anonymous> (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\shandler\js\index.js:208:21)
    at WebSocketManager.emit (events.js:327:22)
    at WebSocketShard.onMessage (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\discord.js\src\client\websocket\WebSocketShard.js:296:56)
    at WebSocket.onMessage (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\ws\lib\event-target.js:132:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\ws\lib\websocket.js:834:20)
    at Receiver.emit (events.js:315:20)
    at Receiver.dataMessage (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\ws\lib\receiver.js:437:14)
    at Receiver.getData (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\ws\lib\receiver.js:367:17)
    at Receiver.startLoop (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\ws\lib\receiver.js:143:22)
    at Receiver._write (C:\Users\Woodw\Desktop\Vibe-Discord-Bot-MAIN-TESTING\node_modules\ws\lib\receiver.js:78:10)
    at writeOrBuffer (internal/streams/writable.js:358:12)
    at Receiver.Writable.write (internal/streams/writable.js:303:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:14472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:14472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by GmBodhi** [comment]
> Notes:
> 
> EXCLUDE:
> 
> > In exclude you must use the file name e.g: `file` not `file.js`
> 
> Docs:
> 
> ```js
> const options = {
>   commandsDir: 'src/slashcommands',
>   showLogs: null,
>   autoRegister: true,
>   exclude: ['file']
> } 
> ```

Will it work when we do `file.js`?

**Comment by Crispy-Cream** [comment]
> > Notes:
> > EXCLUDE:
> > > In exclude you must use the file name e.g: `file` not `file.js`
> > 
> > 
> > Docs:
> > ```js
> > const options = {
> >   commandsDir: 'src/slashcommands',
> >   showLogs: null,
> >   autoRegister: true,
> >   exclude: ['file']
> > } 
> > ```
> 
> Will it work when we do `file.js`?

Nope, it will not do anything. It will only work when you just put the file name.

**Comment by Crispy-Cream** [comment]
Interaction.defer(); isn't working in buttonClick events.

**Comment by GmBodhi** [comment]
Let me know if the interaction is failing

**Comment by Crispy-Cream** [comment]
> Let me know if the interaction is failing

If you run interaction.defer() in a button event like: 

```js
  } else if (button.data.custom_id === "testing") {
    //button.reply(`Hi!`)
    button.defer()
  }
```

The interaction doesn't fail, nothing happens.

**Comment by GmBodhi** [comment]
I think that's the expected behaviour [Docs](https://discord.com/developers/docs/interactions/slash-commands#interaction-response-object-interaction-callback-type)

**Comment by GmBodhi** [comment]
![image](https://user-images.githubusercontent.com/71921036/124547387-ac528480-de49-11eb-9bd9-9540859f93d0.png)

**Comment by Crispy-Cream** [comment]
All documentation has been updated. I need to test the button.reply in the button click event then when I figure that out I can update documentation. https://github.com/GmBodhi/shandler/pull/29 :)

**Comment by Crispy-Cream** [comment]
Have tested isCommand, isComponent, button.update, button.reply. Just need to add documentation.

**Comment by GmBodhi** [comment]
Cool

**Comment by GmBodhi** [comment]
Everything is working without breaks right?
Can I merge to `master`?

**Comment by Crispy-Cream** [comment]
> Everything is working without breaks right?
> Can I merge to `master`?

Yup I have not found any problems. Just working on documentation at the moment :)

**Comment by Crispy-Cream** [comment]
Updated Documentation https://github.com/GmBodhi/shandler/pull/33

Updated Shandler Example Bot https://github.com/GmBodhi/shandler-example-bot

**Comment by Crispy-Cream** [comment]
Closing issue until more things needs to be done.
